# Generated by Django 4.1 on 2022-08-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMakandura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_project_m', models.CharField(max_length=200)),
                ('summery_project_m', models.TextField()),
                ('content_project_m', models.TextField()),
                ('image_project_m', models.ImageField(upload_to='')),
            ],
        ),
    ]
