# Generated by Django 4.1 on 2022-08-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmakandura', '0002_alter_projectmakandura_image_project_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmakandura',
            name='image_project_m',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
