# Generated by Django 4.1 on 2022-09-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmakandura', '0003_alter_projectmakandura_image_project_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmakandura',
            name='content_project_m',
            field=models.JSONField(),
        ),
    ]
