# Generated by Django 4.1 on 2022-08-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pastevent', models.CharField(max_length=200)),
                ('summery_pastevent', models.TextField()),
                ('content_pastevent', models.TextField()),
            ],
        ),
    ]
