# Generated by Django 4.1 on 2022-08-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newspage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summrey', models.TextField()),
                ('content', models.TextField()),
                ('image', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
