# Generated by Django 4.0.5 on 2022-08-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0002_rename_summrey_newspage_summery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
