# Generated by Django 4.0.5 on 2022-08-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0003_alter_newspage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='content',
            field=models.JSONField(),
        ),
    ]
