# Generated by Django 4.0.5 on 2022-08-24 07:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0006_alter_newspage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='content',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8),
        ),
    ]
