# Generated by Django 4.1 on 2022-08-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summery', models.TextField()),
                ('delitel', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
