# Generated by Django 4.1 on 2022-08-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_pastevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastevent',
            old_name='delitel',
            new_name='detils',
        ),
        migrations.RemoveField(
            model_name='pastevent',
            name='photo',
        ),
    ]
