# Generated by Django 4.1 on 2022-08-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_delitel_pastevent_detils_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pastevent',
        ),
    ]
