# Generated by Django 4.1 on 2022-08-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_delete_pastevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='image_project_m',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
