# Generated by Django 4.1 on 2022-08-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_news_image_news_image_project_m'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image_project_m',
            new_name='image',
        ),
    ]
