# Generated by Django 4.0.5 on 2022-08-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_is_active_news_status'),
        ('news', '0008_rename_image_project_m_news_image'),
    ]

    operations = [
    ]
